######################################################################
#                   ╔╦╗┌─┐┬  ┌─┐┌─┐┌─┐┬─┐┌┬┐
#                    ║ ├┤ │  ├┤ ├─┘│ │├┬┘ │
#                    ╩ └─┘┴─┘└─┘┴  └─┘┴└─ ┴
#                   ╔═╗┌─┐┬─┐┌─┐┬  ┬  ┌─┐
#                   ╚═╗│  ├┬┘│ ││  │  └─┐
#                   ╚═╝└─┘┴└─└─┘┴─┘┴─┘└─┘
# by: sourceSCOde
######################################################################

item:
# %%scroll%% is the placeholder for the scroll name
  name: "&2%%scroll%% Teleport Scroll"
  lore:
    - "&aA magic scroll that teleports"
    - "&ayou to &2%%scroll%%"
    - "&e&lRight-click to use."